[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ["py312"]
include = "backend/"

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["apps", "accessproj", "core"]
skip = [".venv"]
