FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential curl netcat-traditional postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/

RUN pip install --default-timeout=300 --no-cache-dir -r requirements.txt

COPY . /app/

RUN chmod +x /app/scripts/*.sh

EXPOSE 8000
