# Generated by Django 5.0.6 on 2025-09-12 10:25

from django.db import migrations, models
import secrets


def generate_auth_tokens(apps, schema_editor):
    Device = apps.get_model('devices', 'Device')
    for device in Device.objects.all():
        device.auth_token = secrets.token_urlsafe(32)
        device.save(update_fields=['auth_token'])


def reverse_generate_auth_tokens(apps, schema_editor):
    Device = apps.get_model('devices', 'Device')
    Device.objects.all().update(auth_token='')


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='auth_token',
            field=models.CharField(max_length=64, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.RunPython(generate_auth_tokens, reverse_generate_auth_tokens),
        migrations.AlterField(
            model_name='device',
            name='auth_token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
