# Generated by Django 5.0.6 on 2025-09-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20250912_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
