# Allowed decisions
DECISIONS = ("ALLOW", "DENY")

# Allowed reasons
REASON_UNKNOWN_GATE     = "UNKNOWN_GATE"
REASON_TOKEN_INVALID    = "TOKEN_INVALID"
REASON_DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND"
REASON_DEVICE_INACTIVE  = "DEVICE_INACTIVE"
REASON_NO_PERMISSION    = "NO_PERMISSION"
REASON_OK               = "OK"
REASON_INVALID_REQUEST  = "INVALID_REQUEST"
REASON_DEVICE_MISMATCH  = "DEVICE_MISMATCH"
REASON_RATE_LIMIT       = "RATE_LIMIT"

REASONS = (
    REASON_UNKNOWN_GATE,
    REASON_TOKEN_INVALID,
    REASON_DEVICE_NOT_FOUND,
    REASON_DEVICE_INACTIVE,
    REASON_NO_PERMISSION,
    REASON_OK,
    REASON_INVALID_REQUEST,
    REASON_DEVICE_MISMATCH,
    REASON_RATE_LIMIT,
)
