name: CI

on:
  push:
    branches: [main, master]
  pull_request:

env:
  PYTHON_VERSION: "3.12"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt -r backend/requirements-dev.txt
      - name: Run linters
        run: |
          make lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt -r backend/requirements-dev.txt
      - name: Collect tests
        run: |
          python -m pytest --collect-only
      - name: Run tests + coverage
        run: |
          make test
      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build backend image
        run: |
          docker build -f backend/Dockerfile backend -t openway/backend:ci
