# Generated by Django 5.0.6 on 2025-10-04 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accesspermission',
            index=models.Index(fields=['access_point', 'user'], name='access_acce_access__9a3b45_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspermission',
            index=models.Index(fields=['access_point', 'group'], name='access_acce_access__df09a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='accesspermission',
            constraint=models.CheckConstraint(check=models.Q(('user__isnull', False), ('group__isnull', False), _connector='OR'), name='ap_perm_user_or_group_not_null'),
        ),
    ]
